# Generated by Django 5.0.6 on 2024-05-30 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('taskid', models.AutoField(db_column='TaskID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('difficulty', models.IntegerField(db_column='Difficulty')),
            ],
        ),

        migrations.CreateModel(
            name='Taskcompletions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('taskid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonplay_app.tasks')),
            ],
            options={
                'unique_together': {('userid', 'taskid')},
            },
        ),
    ]
