# Generated by Django 5.0.3 on 2024-04-01 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonplay_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('achievename', models.CharField(db_column='AchieveName', max_length=255, primary_key=True, serialize=False)),
                ('goal', models.CharField(max_length=255)),
                ('reward', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('taskid', models.AutoField(db_column='TaskID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('difficulty', models.IntegerField(db_column='Difficulty')),
            ],
        ),
        migrations.CreateModel(
            name='Achievementslist',
            fields=[
                ('userid', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pythonplay_app.users')),
                ('achievename', models.ForeignKey(db_column='AchieveName', on_delete=django.db.models.deletion.DO_NOTHING, to='pythonplay_app.achievements')),
            ],
        ),
        migrations.CreateModel(
            name='Taskcompletions',
            fields=[
                ('userid', models.OneToOneField(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pythonplay_app.users')),
                ('taskid', models.ForeignKey(db_column='TaskID', on_delete=django.db.models.deletion.DO_NOTHING, to='pythonplay_app.tasks')),
            ],
        ),
    ]
